[[bin]]
name = "day1"
path = '.\src\bin\day1\main.rs'

[[bin]]
name = "day2"
path = '.\src\bin\day2\main.rs'

[dependencies]
itertools = "0.10.5"
nom = "7.1.3"
regex = "1.8.3"

[package]
edition = "2021"
name = "aoc20"
version = "0.1.0"
